# Use conda-forge to set up the environment and run a pip-check

name: Pip check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pip-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup environment
      run: cp .ci_support/environment.yml environment.yml
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.11'
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        use-mamba: true
    - name: Update environment
      run: mamba env update -n my-env -f environment.yml
    - name: Pip check
      shell: bash -l {0}
      run: |
        pip install --no-deps .
        pip check